from .adverb import Adverb
from .adjective import Adjective
from .article import Article
from .conjunction import Conjunction
from .interjection import Interjection
from .noun import Noun
from .numeral import Numeral
from .preposition import Preposition
from .pronoun import Pronoun
from .verb import Verb
